apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bookapi
        tier: backend
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: app
          image: bookapi.azurecr.io/bookapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              value: "postgresql.postgres.database.azure.com"
            - name: PG_PORT 
              value: "5432"
            - name: PG_USER
              value: "postgres@postgresql"
            - name: PG_PASSWORD 
              value: 'kEYZXMjhEgQh34ZGHzk'
            - name: PG_DATABASE
              value: 'bookapi'
