apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bookapi
        tier: backend
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: app
          image: bookapi.azurecr.io/bookapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              value: "postgres-master.default"
